deployment:
  tasks:
    - export PROJECT_DIR=/home/allankfn/repositories/AllAbout-Front
    - cd $PROJECT_DIR
    - /bin/npm install
    - /bin/npm run build
    - export DEPLOYPATH=/home/allankfn/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH
